#pragma once

/* GENERATED by cbindgen from infinigpu-abi — do not edit. Regenerate: scripts/gen-abi-header.sh */

#include <stdarg.h>
#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>
#include <stdlib.h>

/**
 * A ring descriptor: a fixed 32-byte record referencing one message's payload.
 */
struct Descriptor {
  /**
   * [`msg_type`] tag.
   */
  uint32_t msg_type;
  /**
   * [`desc_flags`] bits.
   */
  uint32_t flags;
  /**
   * Payload length in bytes.
   */
  uint32_t len;
  /**
   * Byte offset of the payload within the ring's data region (ignored when
   * [`desc_flags::INLINE`] is set).
   */
  uint32_t data_offset;
  /**
   * Submission seqno for this descriptor.
   */
  uint64_t seqno;
  /**
   * Absolute guest-physical address of the payload when [`desc_flags::PAYLOAD_ABS`]
   * is set (otherwise 0 / reserved). Lets a large out-of-line body live outside the
   * ring's fixed per-slot payload region.
   */
  uint64_t payload_addr;
};

/**
 * TLV message header (`{type, length}`) for skip-unknown forward-compat. Precedes
 * a fixed or postcard-encoded message body.
 */
struct MsgHeader {
  uint32_t msg_type;
  /**
   * Body length in bytes, not including this header.
   */
  uint32_t length;
};

/**
 * Geometry header describing a command/control ring (magic + ABI + capacity).
 * For the inline-header transport it sits at the ring base; for vfio-user the
 * same values are mirrored in device registers.
 */
struct RingGeometry {
  /**
   * [`crate::ids::DEV_MAGIC`].
   */
  uint32_t magic;
  uint16_t abi_major;
  uint16_t abi_minor;
  /**
   * Number of descriptor slots (power of two).
   */
  uint32_t capacity;
  /**
   * Descriptor stride in bytes ([`DESCRIPTOR_SIZE`]).
   */
  uint32_t desc_stride;
  /**
   * Byte offset of the data region from the ring base.
   */
  uint32_t data_offset;
  /**
   * Length of the data region in bytes.
   */
  uint32_t data_len;
  uint32_t flags;
  uint32_t _reserved;
};

/**
 * `NEGOTIATE` request/response body.
 */
struct Negotiate {
  uint16_t abi_major;
  uint16_t abi_minor;
  /**
   * Requested (or, in the response, granted) capset bitmap ([`capset`]).
   */
  uint32_t capsets;
  uint32_t flags;
  uint32_t _reserved;
};

/**
 * `CTX_CREATE` body.
 */
struct CtxCreate {
  uint32_t ctx_id;
  uint32_t capset_id;
  /**
   * [`api_type`].
   */
  uint32_t api_type;
  uint32_t flags;
};

/**
 * `RESOURCE_CREATE_BLOB` body.
 */
struct ResourceCreateBlob {
  uint32_t res_id;
  uint32_t ctx_id;
  /**
   * [`blob_mem`].
   */
  uint32_t blob_mem;
  uint32_t blob_flags;
  uint64_t size;
};

/**
 * `RESOURCE_ATTACH_BACKING` body — a fixed header followed by `num_entries` [`MemEntry`]s (the
 * guest-physical segments that back a blob). The host records them in its per-VM `ResourceTable`
 * and later resolves each through the IOVA table before any dereference. `num_entries` is bounded
 * by the host (fail-closed) so a hostile guest can't force an unbounded read.
 */
struct AttachBacking {
  uint32_t res_id;
  /**
   * Number of [`MemEntry`]s that follow this header in the payload.
   */
  uint32_t num_entries;
};

/**
 * One guest-physical backing segment (follows an [`AttachBacking`] header). Mirrors virtio-gpu's
 * `virtio_gpu_mem_entry`: an address + length pair. `length` sums (overflow-checked host-side)
 * must cover the blob's declared size.
 */
struct MemEntry {
  uint64_t addr;
  uint64_t length;
};

/**
 * `RESOURCE_MAP_BLOB` body.
 */
struct MapBlob {
  uint32_t res_id;
  uint32_t flags;
  /**
   * Offset into the BAR2 aperture at which to window this blob.
   */
  uint64_t offset;
};

/**
 * `SUBMIT_CMD` body (followed by `payload_len` opaque bytes).
 */
struct SubmitCmd {
  uint32_t ctx_id;
  /**
   * [`encoding`].
   */
  uint32_t encoding;
  uint32_t payload_len;
  uint32_t flags;
  uint64_t seqno;
  /**
   * Wait for this seqno before executing (0 = none).
   */
  uint64_t in_fence;
  /**
   * Signal this seqno on completion (0 = none).
   */
  uint64_t out_fence;
};

/**
 * Inline fence record / `FENCE_WAIT` body.
 */
struct Fence {
  uint32_t ctx_id;
  uint32_t flags;
  uint64_t seqno;
};

/**
 * `SET_SCANOUT_BLOB` body.
 */
struct SetScanoutBlob {
  uint32_t scanout_id;
  uint32_t res_id;
  uint32_t width;
  uint32_t height;
  /**
   * [`format`].
   */
  uint32_t format;
  uint32_t stride;
};

/**
 * `RESOURCE_FLUSH` body — "present"; host imports the blob dma-buf, encodes, and
 * feeds the console relay. Rect is the damaged region.
 */
struct ResourceFlush {
  uint32_t res_id;
  uint32_t x;
  uint32_t y;
  uint32_t w;
  uint32_t h;
  uint32_t _reserved;
};

/**
 * Phase-0 `DISPLAY_CLEAR` payload (see [`encoding::DISPLAY_CLEAR`]): render an
 * `width`×`height` image cleared to `rgba` (linear 0.0–1.0) and DMA-write the
 * resulting `R8G8B8A8` pixels to guest address `scanout_addr`.
 */
struct ClearPresent {
  uint32_t width;
  uint32_t height;
  float rgba[4];
  uint64_t scanout_addr;
};

/**
 * `DISPLAY_SCANOUT` payload (see [`encoding::DISPLAY_SCANOUT`]): the guest's real
 * DRM/KMS driver hands the host a contiguous framebuffer to present. `scanout_addr`
 * is the guest-physical base of the framebuffer (a `dma_addr_t` from
 * `drm_fb_dma_get_gem_addr`); the host reads `pitch * height` bytes and interprets
 * them as `format` ([`format`]). No render is implied — this is a pure 2D scan-out
 * of pixels the guest already produced.
 */
struct ScanoutPresent {
  uint32_t width;
  uint32_t height;
  /**
   * Bytes per row (may exceed `width * 4` for alignment).
   */
  uint32_t pitch;
  /**
   * [`format`] tag; fbcon's default 32-bpp buffer is `XRGB8888` = [`format::B8G8R8X8`].
   */
  uint32_t format;
  /**
   * Guest-physical base address of the framebuffer.
   */
  uint64_t scanout_addr;
};

/**
 * `DISPLAY_SCANOUT_DAMAGE` payload (see [`encoding::DISPLAY_SCANOUT_DAMAGE`]): a
 * [`ScanoutPresent`] **superset** that appends a damage rect. The first four fields plus
 * `scanout_addr` are byte-identical to [`ScanoutPresent`] (same offsets), so a decoder can
 * read the common prefix from either. `dx,dy,dw,dh` describe the only region that changed
 * since the previous present, in the same pixel space as `width`/`height`. The guest fills
 * it from the merged clip `drm_atomic_helper_damage_merged` already computes; a full-frame
 * present sets `dx=dy=0, dw=width, dh=height` (e.g. the first flip after a modeset, or when
 * no damage is known).
 */
struct ScanoutPresentDamaged {
  uint32_t width;
  uint32_t height;
  /**
   * Bytes per row (may exceed `width * 4` for alignment).
   */
  uint32_t pitch;
  /**
   * [`format`] tag; fbcon's default 32-bpp buffer is `XRGB8888` = [`format::B8G8R8X8`].
   */
  uint32_t format;
  /**
   * Guest-physical base address of the framebuffer.
   */
  uint64_t scanout_addr;
  /**
   * Damage rect origin x.
   */
  uint32_t dx;
  /**
   * Damage rect origin y.
   */
  uint32_t dy;
  /**
   * Damage rect width (`dw==width && dh==height` is a full-frame present).
   */
  uint32_t dw;
  /**
   * Damage rect height.
   */
  uint32_t dh;
};

/**
 * `CURSOR_UPDATE` (`msg_type::CURSOR_UPDATE = 0x0042`) body — the guest reports its cursor plane
 * out-of-band so the cursor leaves the primary framebuffer (see
 * `docs/adr/CLIENT-PLANE-COMPOSITOR.md`). The device forwards it to a client-side overlay (the
 * zero-lag path) or composites it host-side (deferred fallback). Position/hotspot are carried for
 * the fallback, for view-only viewers in the multi-client case, and for `WARP` correction — even
 * though a driving client-composite viewer normally draws at its own local pointer. Additive
 * (ABI 0.3); a peer that doesn't negotiate `caps::CURSOR_PLANE` never sends or receives it.
 *
 * The decoder reads it with the `min(payload_len, size_of)` zero-filled rule (ADR-0004), so a
 * future field carved out of `_reserved` never breaks an older host.
 */
struct CursorUpdate {
  /**
   * Which head (`MAX_SCANOUTS == 1` today; cheap future-proofing for multi-head).
   */
  uint32_t scanout_id;
  /**
   * [`cursor_flags`] bits.
   */
  uint32_t flags;
  /**
   * Cursor origin x (`crtc_x`) — **signed**: the hotspot pushes the origin negative at a screen
   * edge, which a `u32` would silently drop.
   */
  int32_t pos_x;
  /**
   * Cursor origin y (`crtc_y`).
   */
  int32_t pos_y;
  /**
   * Hotspot x within the sprite.
   */
  uint16_t hot_x;
  /**
   * Hotspot y within the sprite.
   */
  uint16_t hot_y;
  /**
   * Sprite width in pixels (`0` when `MOVE_ONLY` / hidden).
   */
  uint16_t width;
  /**
   * Sprite height in pixels.
   */
  uint16_t height;
  /**
   * Sprite bytes per row (validated `>= width*4`).
   */
  uint32_t pitch;
  /**
   * [`format`] tag; the DRM cursor default is premultiplied ARGB8888 = [`format::B8G8R8A8`]
   * (the device accepts only this and fails closed otherwise).
   */
  uint32_t format;
  /**
   * Guest-physical address of the ARGB sprite, or a `ResourceTable` res_id when
   * [`cursor_flags::SHAPE_BY_RESID`] is set.
   */
  uint64_t shape_ref;
  /**
   * Additive headroom (0 today).
   */
  uint64_t _reserved;
};

/**
 * `SUBMIT_CMD` payload for [`encoding::VULKAN_VENUSLIKE`] — the Phase-0 own-remoting 3D
 * subset (`docs/adr/3D-ACCEL-IMPLEMENTATION.md`, Step 4/5). A guest names one hand-rolled
 * Vulkan workload ([`vk_op`]); the host **replays it against real Vulkan (ash) on the physical
 * GPU** and DMA-writes the `R8G8B8A8` result to `scanout_addr` for the guest's page-flip —
 * the same present shape as [`ClearPresent`], but the pixels come from GPU pipeline execution,
 * not a fixed clear. This is our own decoder — no Mesa venus / virglrenderer dependency, so it
 * runs on the stock host driver. `bg` is the clear colour (or the triangle's background).
 */
struct VulkanWorkload {
  /**
   * [`vk_op`].
   */
  uint32_t op;
  uint32_t width;
  uint32_t height;
  uint32_t _pad;
  float bg[4];
  uint64_t scanout_addr;
};

/**
 * Trailing header for a [`vk_op::FORWARDED`] draw. Sits immediately after the fixed
 * [`VulkanWorkload`] in the `SUBMIT_CMD` payload and is itself followed, in order, by:
 *   1. vertex-stage SPIR-V — `vertex_spirv_len` bytes (a multiple of 4),
 *   2. fragment-stage SPIR-V — `fragment_spirv_len` bytes,
 *   3. vertex entry-point name — `vertex_entry_len` bytes (incl. trailing NUL),
 *   4. fragment entry-point name — `fragment_entry_len` bytes (incl. trailing NUL).
 * The render target `width`/`height`, clear `bg`, and `scanout_addr` come from the enclosing
 * [`VulkanWorkload`]. All lengths are guest-controlled and MUST be bounds-checked against the
 * actual payload length by the host before use (fail-closed). 24 bytes, 4-byte aligned.
 */
struct ForwardedDrawTail {
  /**
   * Vertices for `draw(vertex_count, 1, 0, 0)` (no vertex buffers — SM-generated).
   */
  uint32_t vertex_count;
  /**
   * [`vk_topology`].
   */
  uint32_t topology;
  /**
   * Byte length of the vertex-stage SPIR-V blob that follows.
   */
  uint32_t vertex_spirv_len;
  /**
   * Byte length of the fragment-stage SPIR-V blob.
   */
  uint32_t fragment_spirv_len;
  /**
   * Byte length of the vertex entry-point name (incl. trailing NUL).
   */
  uint32_t vertex_entry_len;
  /**
   * Byte length of the fragment entry-point name (incl. trailing NUL).
   */
  uint32_t fragment_entry_len;
};

/**
 * Trailing header for a [`vk_op::FORWARDED_CMDLIST`] draw (Phase-2b command list). Sits
 * immediately after the fixed [`VulkanWorkload`] and is followed, **in this exact order**, by:
 *   1. `attr_count` × [`VertexAttrWire`]  (12 B each, 4-aligned),
 *   2. `draw_count` × [`DrawCmdWire`]     (32 B each, 4-aligned),
 *   3. vertex-stage SPIR-V — `vertex_spirv_len` bytes (multiple of 4),
 *   4. fragment-stage SPIR-V — `fragment_spirv_len` bytes,
 *   5. vertex-buffer data — `vertex_data_len` bytes (arbitrary length),
 *   6. index-buffer data — `index_data_len` bytes (0 ⇒ non-indexed draws),
 *   7. vertex entry-point name — `vertex_entry_len` bytes (incl. trailing NUL),
 *   8. fragment entry-point name — `fragment_entry_len` bytes (incl. trailing NUL).
 * The 4-byte-multiple sections (attrs, draws, `tex_count`×[`TextureDescWire`], both SPIR-V blobs)
 * come first so each stays 4-aligned relative to the tail; the arbitrary-length byte blobs (vertex
 * data, index data, both entry names, push-const bytes, UBO bytes, then the concatenated texture
 * pixels) come last, read as raw bytes so their odd lengths never misalign a fixed-layout array.
 * Full order:
 *   attrs[attr_count] · draws[draw_count] · texs[tex_count] ·
 *   vSPIR-V · fSPIR-V · vertex data · index data · vertex entry · fragment entry ·
 *   push-const bytes · UBO bytes (`ubo_len`) · texture pixels (RGBA8, concatenated in `texs` order).
 * `push_const_len` is a transform block (ABI 0.9); `tex_count` textures (ABI 0.10) bind a sampled
 * image at binding `tex_binding + 2i` and a sampler at `tex_binding + 2i + 1`; the UBO (ABI 0.11)
 * binds at `ubo_binding` (VERTEX|FRAGMENT). The host builds the descriptor-set-0 layout **dynamically**
 * from whichever resources are present at their declared bindings, so a UBO and a texture compose in
 * one set (e.g. UBO@0, image@1, sampler@2). The UBO byte blob is fixed-length (`ubo_len`); the texture
 * pixels stay the terminal derived region (length = Σ `TextureDescWire::data_len`). Every length is
 * guest-controlled and MUST be bounds-checked against the actual payload length before use
 * (fail-closed).
 *
 * `vertex_stride == 0` means "no vertex buffer" (bufferless, like [`ForwardedDrawTail`] — the
 * shader synthesizes geometry); otherwise binding 0 has that stride and the `attr_count`
 * attributes describe it. 68 bytes, 4-byte aligned.
 */
struct ForwardedCmdListTail {
  /**
   * Byte length of the vertex-stage SPIR-V blob.
   */
  uint32_t vertex_spirv_len;
  /**
   * Byte length of the fragment-stage SPIR-V blob.
   */
  uint32_t fragment_spirv_len;
  /**
   * Byte length of the vertex entry-point name (incl. trailing NUL).
   */
  uint32_t vertex_entry_len;
  /**
   * Byte length of the fragment entry-point name (incl. trailing NUL).
   */
  uint32_t fragment_entry_len;
  /**
   * Bytes per vertex (binding 0 stride); `0` ⇒ bufferless (no vertex buffer bound).
   */
  uint32_t vertex_stride;
  /**
   * Number of [`VertexAttrWire`]s that follow (0 when bufferless).
   */
  uint32_t attr_count;
  /**
   * Byte length of the vertex-buffer data blob.
   */
  uint32_t vertex_data_len;
  /**
   * Byte length of the index-buffer data blob; `0` ⇒ non-indexed draws.
   */
  uint32_t index_data_len;
  /**
   * [`index_type`] (ignored when `index_data_len == 0`).
   */
  uint32_t index_type;
  /**
   * Number of [`DrawCmdWire`]s that follow (≥ 1 for anything to render).
   */
  uint32_t draw_count;
  /**
   * [`vk_topology`] for every draw in the list.
   */
  uint32_t topology;
  /**
   * Depth-test state as a [`depth_flags`] bitfield (Phase-2d): `TEST | WRITE | (compare <<
   * COMPARE_SHIFT)`. `0` ⇒ no depth buffer (2D / painter's order — the older-guest default, since
   * this field was zero-`_reserved` in ABI 0.8's first cut). A host adds a depth attachment iff
   * `TEST | WRITE` is set.
   */
  uint32_t depth_flags;
  /**
   * Byte length of the push-constant block (ABI 0.9) — section 9, appended after the fragment
   * entry name. `0` ⇒ no push constants. The host builds a pipeline-layout push-constant range
   * (VERTEX|FRAGMENT, offset 0, this size) and `cmd_push_constants` these bytes before the draws.
   * Carries a shader's transform block (an MVP matrix); bounded ≤ the device's
   * `maxPushConstantsSize` host-side.
   */
  uint32_t push_const_len;
  /**
   * Number of sampled textures (ABI 0.10). `0` ⇒ no textures. Each is a [`TextureDescWire`] (in the
   * fixed-array region after the draws) plus its RGBA8 pixels (in the trailing pixel region). Texture
   * `i` binds at descriptor set 0 binding `tex_binding + 2i` (sampled image) + `tex_binding + 2i + 1`
   * (sampler), matching a WGSL `texture_2d`/`sampler` pair. Host-bounded (fail-closed).
   */
  uint32_t tex_count;
  /**
   * Byte length of the uniform-buffer (UBO) block (ABI 0.11) — a fixed-length byte blob appended
   * after the push constants and before the trailing texture pixels. `0` ⇒ no UBO. The host uploads
   * these bytes into a `UNIFORM_BUFFER` bound at descriptor set 0 binding [`ubo_binding`]
   * (VERTEX|FRAGMENT), so a shader's `var<uniform>` block (e.g. per-frame matrices) reads them.
   */
  uint32_t ubo_len;
  /**
   * Descriptor-set-0 binding the UBO occupies (ABI 0.11). Ignored when `ubo_len == 0`. Must not fall
   * inside the texture's binding range `[tex_binding .. tex_binding + 2*tex_count)`.
   */
  uint32_t ubo_binding;
  /**
   * Base descriptor-set-0 binding of texture 0's sampled image (ABI 0.11); sampler at `tex_binding+1`,
   * texture `i` at `tex_binding + 2i` / `+ 2i + 1`. `0` (the pre-0.11 default) ⇒ image@0 / sampler@1,
   * byte- and semantics-identical to ABI 0.10 texture-only command lists. Lets a UBO and a texture
   * occupy the same set at distinct bindings (UBO@0, image@1, sampler@2), which real apps need.
   */
  uint32_t tex_binding;
};

/**
 * One vertex attribute in a [`ForwardedCmdListTail`] (follows the tail). Describes one input the
 * vertex shader reads from binding 0. 12 bytes, 4-aligned.
 */
struct VertexAttrWire {
  /**
   * `layout(location = N)` in the vertex shader.
   */
  uint32_t location;
  /**
   * [`vk_vformat`].
   */
  uint32_t format;
  /**
   * Byte offset of this attribute within one vertex.
   */
  uint32_t offset;
};

/**
 * One draw command in a [`ForwardedCmdListTail`] (follows the attribute array). Mirrors a guest
 * `vkCmdDraw`/`vkCmdDrawIndexed`. Whether it is indexed is decided list-wide by
 * `index_data_len != 0` (a single index buffer serves the list — the common "one mesh, many draws"
 * shape). 32 bytes, 4-aligned.
 */
struct DrawCmdWire {
  /**
   * `vertex_count` (non-indexed) or `index_count` (indexed).
   */
  uint32_t count;
  /**
   * Instance count (`0` is treated as `1` host-side).
   */
  uint32_t instance_count;
  /**
   * `first_vertex` (non-indexed) or `first_index` (indexed).
   */
  uint32_t first;
  /**
   * Value added to every index before fetching a vertex (indexed only). **Signed.**
   */
  int32_t vertex_offset;
  /**
   * Viewport x (pixels).
   */
  float vp_x;
  /**
   * Viewport y (pixels).
   */
  float vp_y;
  /**
   * Viewport width (pixels); `0` ⇒ use the full render target.
   */
  float vp_w;
  /**
   * Viewport height (pixels).
   */
  float vp_h;
};

/**
 * One sampled texture in a [`ForwardedCmdListTail`] (in the fixed-array region after the draws).
 * Its `data_len == width*height*4` RGBA8 pixels live in the trailing pixel region, concatenated in
 * texture order. 16 bytes, 4-aligned.
 */
struct TextureDescWire {
  uint32_t width;
  uint32_t height;
  /**
   * RGBA8 byte length (`width*height*4`); the host validates the product.
   */
  uint32_t data_len;
  /**
   * [`sampler_flags`].
   */
  uint32_t sampler_flags;
};
