#pragma once

/* GENERATED by cbindgen from infinigpu-abi — do not edit. Regenerate: scripts/gen-abi-header.sh */

#include <stdarg.h>
#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>
#include <stdlib.h>

/**
 * A ring descriptor: a fixed 32-byte record referencing one message's payload.
 */
struct Descriptor {
  /**
   * [`msg_type`] tag.
   */
  uint32_t msg_type;
  /**
   * [`desc_flags`] bits.
   */
  uint32_t flags;
  /**
   * Payload length in bytes.
   */
  uint32_t len;
  /**
   * Byte offset of the payload within the ring's data region (ignored when
   * [`desc_flags::INLINE`] is set).
   */
  uint32_t data_offset;
  /**
   * Submission seqno for this descriptor.
   */
  uint64_t seqno;
  uint64_t _reserved;
};

/**
 * TLV message header (`{type, length}`) for skip-unknown forward-compat. Precedes
 * a fixed or postcard-encoded message body.
 */
struct MsgHeader {
  uint32_t msg_type;
  /**
   * Body length in bytes, not including this header.
   */
  uint32_t length;
};

/**
 * Geometry header describing a command/control ring (magic + ABI + capacity).
 * For the inline-header transport it sits at the ring base; for vfio-user the
 * same values are mirrored in device registers.
 */
struct RingGeometry {
  /**
   * [`crate::ids::DEV_MAGIC`].
   */
  uint32_t magic;
  uint16_t abi_major;
  uint16_t abi_minor;
  /**
   * Number of descriptor slots (power of two).
   */
  uint32_t capacity;
  /**
   * Descriptor stride in bytes ([`DESCRIPTOR_SIZE`]).
   */
  uint32_t desc_stride;
  /**
   * Byte offset of the data region from the ring base.
   */
  uint32_t data_offset;
  /**
   * Length of the data region in bytes.
   */
  uint32_t data_len;
  uint32_t flags;
  uint32_t _reserved;
};

/**
 * `NEGOTIATE` request/response body.
 */
struct Negotiate {
  uint16_t abi_major;
  uint16_t abi_minor;
  /**
   * Requested (or, in the response, granted) capset bitmap ([`capset`]).
   */
  uint32_t capsets;
  uint32_t flags;
  uint32_t _reserved;
};

/**
 * `CTX_CREATE` body.
 */
struct CtxCreate {
  uint32_t ctx_id;
  uint32_t capset_id;
  /**
   * [`api_type`].
   */
  uint32_t api_type;
  uint32_t flags;
};

/**
 * `RESOURCE_CREATE_BLOB` body.
 */
struct ResourceCreateBlob {
  uint32_t res_id;
  uint32_t ctx_id;
  /**
   * [`blob_mem`].
   */
  uint32_t blob_mem;
  uint32_t blob_flags;
  uint64_t size;
};

/**
 * `RESOURCE_MAP_BLOB` body.
 */
struct MapBlob {
  uint32_t res_id;
  uint32_t flags;
  /**
   * Offset into the BAR2 aperture at which to window this blob.
   */
  uint64_t offset;
};

/**
 * `SUBMIT_CMD` body (followed by `payload_len` opaque bytes).
 */
struct SubmitCmd {
  uint32_t ctx_id;
  /**
   * [`encoding`].
   */
  uint32_t encoding;
  uint32_t payload_len;
  uint32_t flags;
  uint64_t seqno;
  /**
   * Wait for this seqno before executing (0 = none).
   */
  uint64_t in_fence;
  /**
   * Signal this seqno on completion (0 = none).
   */
  uint64_t out_fence;
};

/**
 * Inline fence record / `FENCE_WAIT` body.
 */
struct Fence {
  uint32_t ctx_id;
  uint32_t flags;
  uint64_t seqno;
};

/**
 * `SET_SCANOUT_BLOB` body.
 */
struct SetScanoutBlob {
  uint32_t scanout_id;
  uint32_t res_id;
  uint32_t width;
  uint32_t height;
  /**
   * [`format`].
   */
  uint32_t format;
  uint32_t stride;
};

/**
 * `RESOURCE_FLUSH` body — "present"; host imports the blob dma-buf, encodes, and
 * feeds the console relay. Rect is the damaged region.
 */
struct ResourceFlush {
  uint32_t res_id;
  uint32_t x;
  uint32_t y;
  uint32_t w;
  uint32_t h;
  uint32_t _reserved;
};

/**
 * Phase-0 `DISPLAY_CLEAR` payload (see [`encoding::DISPLAY_CLEAR`]): render an
 * `width`×`height` image cleared to `rgba` (linear 0.0–1.0) and DMA-write the
 * resulting `R8G8B8A8` pixels to guest address `scanout_addr`.
 */
struct ClearPresent {
  uint32_t width;
  uint32_t height;
  float rgba[4];
  uint64_t scanout_addr;
};

/**
 * `DISPLAY_SCANOUT` payload (see [`encoding::DISPLAY_SCANOUT`]): the guest's real
 * DRM/KMS driver hands the host a contiguous framebuffer to present. `scanout_addr`
 * is the guest-physical base of the framebuffer (a `dma_addr_t` from
 * `drm_fb_dma_get_gem_addr`); the host reads `pitch * height` bytes and interprets
 * them as `format` ([`format`]). No render is implied — this is a pure 2D scan-out
 * of pixels the guest already produced.
 */
struct ScanoutPresent {
  uint32_t width;
  uint32_t height;
  /**
   * Bytes per row (may exceed `width * 4` for alignment).
   */
  uint32_t pitch;
  /**
   * [`format`] tag; fbcon's default 32-bpp buffer is `XRGB8888` = [`format::B8G8R8X8`].
   */
  uint32_t format;
  /**
   * Guest-physical base address of the framebuffer.
   */
  uint64_t scanout_addr;
};
